# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('indicator_name', models.CharField(max_length=200)),
                ('indicator_code', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'country_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='worldbankdata',
            constraint=models.UniqueConstraint(fields=('country_code', 'indicator_code', 'year'), name='unique_country_indicator_year'),
        ),
    ]